name: algerian_workers_user_app
description: Application utilisateurs pour la plateforme Algerian Workers - Recherche gratuite de travailleurs qualifiés
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  
  # État et gestion des données
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.8.4
  
  # UI et design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  photo_view: ^0.14.0
  video_player: ^2.8.1
  
  # Cartographie et géolocalisation
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.1.0
  
  # Paiements
  stripe_platform_interface: ^8.0.0
  stripe_android: ^8.0.0
  stripe_ios: ^8.0.0
  
  # Utilitaires
  intl: ^0.18.1
  uuid: ^4.2.1
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  http: ^1.1.2
  dio: ^5.4.0
  
  # Validation et formulaires
  form_validator: ^2.1.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  
  # Animations
  lottie: ^2.7.0
  rive: ^0.12.4
  flutter_animate: ^4.3.0
  
  # Gestion des erreurs
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  
  # Tests
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700